// @generated
// This file is @generated by prost-build.
/// Persisted EVM account-state changes for one block, keyed by the account
/// actually changed (never by call-to address). Only changes that survived
/// execution are included: successful calls, plus the gas / nonce effects of
/// failed transactions and the EIP-7702 authorization effects that persist
/// regardless of transaction status. Block-level (reward, system call) changes
/// are included too. See README "Semantics".
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateChanges {
    #[prost(message, optional, tag="1")]
    pub block: ::core::option::Option<BlockInfo>,
    #[prost(message, repeated, tag="10")]
    pub storage_changes: ::prost::alloc::vec::Vec<StorageChange>,
    #[prost(message, repeated, tag="11")]
    pub balance_changes: ::prost::alloc::vec::Vec<BalanceChange>,
    #[prost(message, repeated, tag="12")]
    pub nonce_changes: ::prost::alloc::vec::Vec<NonceChange>,
    #[prost(message, repeated, tag="13")]
    pub code_changes: ::prost::alloc::vec::Vec<CodeChange>,
    #[prost(message, repeated, tag="14")]
    pub set_code_authorizations: ::prost::alloc::vec::Vec<SetCodeAuthorization>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockInfo {
    #[prost(uint64, tag="1")]
    pub number: u64,
    #[prost(bytes="vec", tag="2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    /// unix seconds
    #[prost(uint64, tag="4")]
    pub timestamp: u64,
    #[prost(bytes="vec", tag="5")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub coinbase: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="7")]
    pub transaction_count: u32,
}
/// Provenance shared by every change record.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Origin {
    /// block-global execution ordinal
    #[prost(uint64, tag="1")]
    pub ordinal: u64,
    #[prost(enumeration="Scope", tag="2")]
    pub scope: i32,
    /// empty for system call / block scope
    #[prost(bytes="vec", tag="3")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="4")]
    pub tx_index: u32,
    /// sf.ethereum.type.v2.TransactionTraceStatus (0 when no tx)
    #[prost(int32, tag="5")]
    pub tx_status: i32,
    #[prost(uint32, tag="6")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageChange {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes
    #[prost(bytes="vec", tag="2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes, may be empty (= zero)
    #[prost(bytes="vec", tag="3")]
    pub old_value: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes, may be empty (= zero)
    #[prost(bytes="vec", tag="4")]
    pub new_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="10")]
    pub origin: ::core::option::Option<Origin>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceChange {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// decimal wei, "0" when absent
    #[prost(string, tag="2")]
    pub old_value: ::prost::alloc::string::String,
    /// decimal wei, "0" when absent
    #[prost(string, tag="3")]
    pub new_value: ::prost::alloc::string::String,
    /// sf.ethereum.type.v2.BalanceChange.Reason
    #[prost(int32, tag="4")]
    pub reason: i32,
    #[prost(message, optional, tag="10")]
    pub origin: ::core::option::Option<Origin>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NonceChange {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub old_value: u64,
    #[prost(uint64, tag="3")]
    pub new_value: u64,
    #[prost(message, optional, tag="10")]
    pub origin: ::core::option::Option<Origin>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CodeChange {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub old_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub new_hash: ::prost::alloc::vec::Vec<u8>,
    /// full bytecode after the change (empty = no code)
    #[prost(bytes="vec", tag="4")]
    pub new_code: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="10")]
    pub origin: ::core::option::Option<Origin>,
}
/// EIP-7702 authorization as carried by a TRX_TYPE_SET_CODE transaction.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetCodeAuthorization {
    #[prost(bytes="vec", tag="1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub tx_index: u32,
    /// position in the authorization list
    #[prost(uint32, tag="3")]
    pub index: u32,
    /// recovered signer (may be empty when discarded)
    #[prost(bytes="vec", tag="4")]
    pub authority: ::prost::alloc::vec::Vec<u8>,
    /// address delegated to (may be empty on early BSC blocks)
    #[prost(bytes="vec", tag="5")]
    pub delegate: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="6")]
    pub nonce: u64,
    #[prost(bool, tag="7")]
    pub discarded: bool,
    #[prost(int32, tag="8")]
    pub tx_status: i32,
}
/// Where in the block a change came from.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Scope {
    Unspecified = 0,
    /// Successful transaction, non-reverted call.
    Tx = 1,
    /// Failed/reverted transaction: gas balance changes and sender nonce that persist anyway.
    TxFailedPersistent = 2,
    /// EIP-7702 authorization nonce/code change on a failed transaction (persists anyway).
    Tx7702 = 3,
    /// Block.system_calls (e.g. EIP-2935 history storage, EIP-4788 beacon root).
    SystemCall = 4,
    /// Block.balance_changes / Block.code_changes (rewards, withdrawals, fork upgrades).
    Block = 5,
}
impl Scope {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Scope::Unspecified => "SCOPE_UNSPECIFIED",
            Scope::Tx => "SCOPE_TX",
            Scope::TxFailedPersistent => "SCOPE_TX_FAILED_PERSISTENT",
            Scope::Tx7702 => "SCOPE_TX_7702",
            Scope::SystemCall => "SCOPE_SYSTEM_CALL",
            Scope::Block => "SCOPE_BLOCK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCOPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SCOPE_TX" => Some(Self::Tx),
            "SCOPE_TX_FAILED_PERSISTENT" => Some(Self::TxFailedPersistent),
            "SCOPE_TX_7702" => Some(Self::Tx7702),
            "SCOPE_SYSTEM_CALL" => Some(Self::SystemCall),
            "SCOPE_BLOCK" => Some(Self::Block),
            _ => None,
        }
    }
}
/// One physical ClickHouse row contains the entire account-filtered block.
/// Nested fields deliberately remain in this table, so no reader can observe
/// half of a block's account updates. Consumers require finalized input and
/// validate parent/hash continuity; _blocks_ is not a publication marker.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockState {
    #[prost(uint64, tag="1")]
    pub number: u64,
    #[prost(string, tag="2")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub timestamp: u64,
    #[prost(string, tag="5")]
    pub state_root: ::prost::alloc::string::String,
    #[prost(int32, tag="6")]
    pub producer_version: i32,
    /// Canonical, sorted account list. Empty is rejected by map_block_state.
    #[prost(string, tag="7")]
    pub accounts: ::prost::alloc::string::String,
    #[prost(uint32, tag="8")]
    pub schema_version: u32,
    #[prost(message, repeated, tag="10")]
    pub storage: ::prost::alloc::vec::Vec<StorageValue>,
    #[prost(message, repeated, tag="11")]
    pub balances: ::prost::alloc::vec::Vec<BalanceValue>,
    #[prost(message, repeated, tag="12")]
    pub nonces: ::prost::alloc::vec::Vec<NonceValue>,
    #[prost(message, repeated, tag="13")]
    pub codes: ::prost::alloc::vec::Vec<CodeValue>,
    /// These accounts require proof-backed reconciliation before publication.
    #[prost(message, repeated, tag="14")]
    pub lifecycle: ::prost::alloc::vec::Vec<LifecycleEffect>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageValue {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub slot: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceValue {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    /// exact decimal wei; no float conversion
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NonceValue {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub value: u64,
    #[prost(uint64, tag="3")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CodeValue {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub hash: ::prost::alloc::string::String,
    /// hex, "0x" explicitly means empty bytecode
    #[prost(string, tag="3")]
    pub code: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LifecycleEffect {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub ordinal: u64,
}
// @@protoc_insertion_point(module)
